name: CI

on:
  push:
    branches: [main, release/*]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    # Run each command in parallel with the same setup steps.
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        config:
          # Specify names so that the GitHub branch protection settings for
          # required checks don't need to change if we ever change the commands used.
          - name: lint
            command: |
              # lint steps
              npm run lint
          - name: build
            command: npm run build

    name: ${{ matrix.config.name }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v3.5.2

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.17

      - name: Restore cache
        uses: actions/cache@v3.3.1
        with:
          path: |
            **/node_modules
          key: v5-${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v5-${{ runner.os }}-npm-

      - run: npm i

      - run: ${{ matrix.config.command }}

  storybook:
    name: storybook (ubuntu-20.04)
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0 # Required for Chromatic
          lfs: true

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.17
      - run: corepack enable yarn

      - name: Restore cache
        uses: actions/cache@v3.3.1
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: v5-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v5-${{ runner.os }}-yarn-

      - run: yarn install --immutable

      - run: yarn workspace @base run storybook:build

      # Chromatic only runs on pushes or pulls to our source repo
      - uses: chromaui/action@v1
        if: ${{ github.event.repository.full_name == 'foxglove/studio' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: f50040a29fb8
          storybookBuildDir: storybook-static
          autoAcceptChanges: main
          exitOnceUploaded: true

  integration:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    name: integration (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          lfs: true

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.17
      - run: corepack enable yarn

      - name: Restore cache
        uses: actions/cache@v3.3.1
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: v5-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v5-${{ runner.os }}-yarn-

      - run: yarn install --immutable

      - name: test:integration
        if: matrix.os == 'ubuntu-20.04'
        uses: GabrielBB/xvfb-action@v1.6
        with:
          working-directory: ./
          run: yarn run test:integration

      - name: test:web-integration
        if: matrix.os == 'ubuntu-20.04'
        run: yarn run test:web-integration

      - name: test:integration
        if: matrix.os != 'ubuntu-20.04'
        run: yarn run test:integration
