name: CI

on:
  push:
    branches: [main, release/*]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    # Run each command in parallel with the same setup steps.
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        config:
          # Specify names so that the GitHub branch protection settings for
          # required checks don't need to change if we ever change the commands used.
          - name: lint
            command: |
              # lint steps
              npm run lint
          - name: build
            command: npm run build

    name: ${{ matrix.config.name }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v3.5.2

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 20.3.1

      - name: Restore cache
        uses: actions/cache@v3.3.1
        with:
          path: |
            **/node_modules
          key: v5-${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v5-${{ runner.os }}-npm-

      - run: npm i

      - run: ${{ matrix.config.command }}